# For information on uploading release asset, see: https://github.com/softprops/action-gh-release

name: Release Linux

on:
  release:
    types: [published]
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.19.0
      - name: Build linux package
        run: |
          export CIBW_BUILD='cp38-* cp310-*'
          python -m cibuildwheel --platform=linux --archs=x86_64 --output-dir=dist
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: release
          token: ${{ secrets.GITHUB_TOKEN }}